// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wdXRndap29bYp1UdWnJi27tam9--Xns',
    appId: '1:687429059252:android:79937c0e8af1c7d4a40de1',
    messagingSenderId: '687429059252',
    projectId: 'csp-chatting-app',
    storageBucket: 'csp-chatting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqP_CrsgpznX-1FSfL3gRjd8pRK21DTwM',
    appId: '1:687429059252:ios:f97e765f5e477496a40de1',
    messagingSenderId: '687429059252',
    projectId: 'csp-chatting-app',
    storageBucket: 'csp-chatting-app.appspot.com',
    androidClientId: '687429059252-a3pg7jj6ngtarbcrj5cu39v83vffajol.apps.googleusercontent.com',
    iosClientId: '687429059252-o1c7g0m8fsbts56sol6ot5as3ohuvge1.apps.googleusercontent.com',
    iosBundleId: 'com.csp.chat.chattingApplication',
  );
}
